name: Test-Build
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install library
      - name: Install lib
        run: |
          pip install requests
          pip install pytz
 
      # Run the Python
      - name: Run the Python
        run: |
          python3 main.py
     
